export const SITE = {
  website: "https://furkanbostanci.com",
  base: "",
  author: "Furkan Bostancı",
  profile: "https://github.com/steetstyle",
  desc: "Hello! I’m Furkan Bostancı",
  title: "Furkan Bostancı",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/steetstyle/doctolio/tree/main/src/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Istanbul",
} as const;
